### ISSUE TITLE
Does not work for Cross Domain queries

### ISSUE THREAD

**Issue by matthiasctx** [inorganik/digest-auth-request#10]
Reason is that XMLHTTPRequest.getAllResponseHeaders() is not allowed to return the digest auth http headers in case it is a x-domain request.
Read: http://stackoverflow.com/questions/7462968/restrictions-of-xmlhttprequests-getresponseheader

**Comment by inorganik** [comment]
XMLHttpRequest Level 2 is simply a standard, you don't have to do anything to implement it, that's up to the browsers - see http://caniuse.com/#feat=xhr2 If you're using a modern browser, it's already implemented for free.

If you're testing this lib in IE 8/9 or Opera mini and having problems, that could be why. Otherwise, there are a whole lot of other reasons you could be having trouble making cross-domain requests. I suggest you read up on CORS. https://cloud.google.com/storage/docs/cross-origin

Good luck.
