### ISSUE TITLE
Bug in parsing

### ISSUE THREAD

**Issue by eppleton** [inorganik/digest-auth-request#12]
When parsing the response headers you do a split using "=". If the nonce contains "=" the extracted nonce will be incorrect.

**Comment by inorganik** [comment]
The nonce should never contain a "=" because that's how headers are assigned.

**Comment by dukescript** [comment]
Well, Toni filed this bug, because there are servers which indeed return a "=" in the nonce. Maybe they shouldn't, but I don't think it's illegal according to the spec, and anyway - they do. One example is the wildfly server admin interface (http://wildfly.org). So in order to be useful, the library should be able to deal with that.

**Comment by inorganik** [comment]
@dukescript, this library has been very useful for me and lots of others. However, given your case, I rewrote how the script parses headers. So this issue should be fixed now. I also added logging so you can inspect what the parsed headers look like. To turn logging off, set `loggingOn` to false. 

Could you and @eppleton please test this against your wildfly setup, to make sure it works, and let me know if everything is fine so I can re-close.
