### ISSUE TITLE
Getting 401 using the library

### ISSUE THREAD

**Issue by unaor** [inorganik/digest-auth-request#13]
I hope you still maintain the library but a simple implementation is not working for me
var req = new digestAuthRequest('GET', url, 'tester', 'tester');
is giving back 401 while the same in cURL is working
i dont know if its related but in cURL im passing the credencials like this 'tester:tester'

**Comment by inorganik** [comment]
I used this on a client project that had a server using digest - that was over a year ago and I don't have access to test with it anymore. But it worked great then and it's worked for lots of people since. 

You can at least do some basic debugging. Did you turn logging on? Did you get the digest headers back? If so, what were they?

**Comment by inorganik** [comment]
I just updated the script to log how it parses the returned headers, and as well I fixed a parsing issue. So please pull the latest version, and try again. Logging is turned on out of the box, so you shouldn't have to type any console.logs. You can turn it off by setting `loggingOn` to false.
