### ISSUE TITLE
Inject dependency "CryptoJS"?

### ISSUE THREAD

**Issue by LesediM** [inorganik/digest-auth-request#30]
I am facing an issue where CryptoJS is undefined and `require('crypto-js')` fails with error:

> Uncaught Error: Module name "crypto-js" has not been loaded yet for context: _. Use require([])

Can the dependency be injected rather?

I did reference the require md5.js file before the digestAuthRequest.js file in the header

**Comment by inorganik** [comment]
It's been quite a while since I used this or worked on it (just did a version bump in December). 

The modularization of this lib is probably out of date. There is this block near the top:
```js
if (typeof CryptoJS === 'undefined' && typeof require === 'function') {
  var CryptoJS = require('crypto-js');
}
```
It's calling require, which may not be defined because it's a commonjs convention, not built-in to javascript. If you are using ES6 you could try
```js
import { CryptoJS } from 'crypto-js';
```
or any other way that you are importing/requiring libs in your project. 

You might also try moving `md5` out of `devDependencies` in package.json and into `dependencies`, and then reinstall debugout. Hopefully that helps

**Comment by LesediM** [comment]
Thank you
